### ISSUE TITLE
Number of timer events

### ISSUE THREAD

**Issue by danxciting** [alextaujenis/RBD_Timer#3]
Up to how many timer events (e.g. RBD::Timer timer_A, timer_B,...) can I make with this library?
This library has been a great help for our group in our projects.
Thanks!

**Comment by alextaujenis** [comment]
I don't have a direct answer of how many timers you can use, only some guidelines on how to identify that limit. You can initialize as many timers as you'd like until:
- You run out of program or memory space because of the size of your sketch, or
- You notice the timers losing resolution and firing events too far behind when they should

Running out of program or memory space depends upon what board you use. An Arduino Mega2560 can hold many more timers compared to an Arduino Micro. 

Losing resolution and having events fire too late would depend upon how you write code inside of loop(). Since this is a millisecond timer it probably doesn't matter as much. It would affect you more if this timer counted micros(). The description in the docs goes into detail about how this is a [Soft Real-Time library](http://robotsbigdata.com/docs-arduino-timer.html#soft-real-time).
